source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.1"

gem "rails", "~> 7.0.2", ">= 7.0.2.3"
gem "sprockets-rails"
gem "sqlite3", "~> 1.4"
gem "puma", "~> 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem 'bootstrap', '~> 5.1', '>= 5.1.3'
gem 'jquery-rails'
gem 'webpacker', '~> 5.4', '>= 5.4.3'
gem 'stock_quote', '~> 3.0'
gem 'finnhub_ruby', '~> 1.1.15'
gem 'json', '~> 2.6', '>= 2.6.1'
gem 'devise', '~> 4.8', '>= 4.8.1'

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do

  gem "web-console"

end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
